<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

if($this->helper('Originalapp\Hideprice\Helper\Data')->isActivated()):

	$productId = $block->getSaleableItem()->getId();
	
	/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
	/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
	$priceModel = $block->getPriceType('regular_price');
	
	/* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
	    'price_id'          => $block->getPriceId('product-price-'),
	    'include_container' => true
	]);
	?>
<?php endif;?>